spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhufeng8407/config-repo.git
          username: zhufeng8407
          password: mumumu8407
          basedir: /Users/zhufeng/git/config
  rabbitmq:
    addresses: 10.211.55.4:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 1500
server:
  port: 8991
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:8671/eureka/
management:
  endpoints: 
    web:
      exposure:
        include: "*"